spring:
  application:
    name: customer-service

  profiles:
    active: dev

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: root

  # JPA Configuration

  jpa:
    show-sql: true

  # SQL Initialization

  sql:
    init:
      mode: always

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"  # This exposes all endpoints