-- =============================================
-- Customer Table Schema for H2 Database
-- This script is idempotent and safe for production use
-- =============================================

-- Create customer table if it doesn't exist
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    address VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_customer_email UNIQUE (email)
);

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_customer_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customer_name ON customers(last_name, first_name);

-- Add column comments (H2 supports comments with COMMENT ON)
COMMENT ON TABLE customers IS 'Stores customer information';
COMMENT ON COLUMN customers.id IS 'Primary key';
COMMENT ON COLUMN customers.first_name IS 'Customer''s first name';
COMMENT ON COLUMN customers.last_name IS 'Customer''s last name';
COMMENT ON COLUMN customers.email IS 'Customer''s email address (must be unique)';
COMMENT ON COLUMN customers.phone IS 'Customer''s contact number';
COMMENT ON COLUMN customers.address IS 'Customer''s physical address';
COMMENT ON COLUMN customers.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN customers.updated_at IS 'Timestamp when the record was last updated';
COMMENT ON COLUMN customers.created_by IS 'User who created the record';
COMMENT ON COLUMN customers.updated_by IS 'User who last updated the record';
COMMENT ON COLUMN customers.is_deleted IS 'Soft delete flag';
COMMENT ON COLUMN customers.version IS 'Optimistic locking version';
